import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

import { Trip, DayLocation, TripFeature } from "../../contexts/TripContext"

// Helper to get day items
const getDayItems = (
  dayId: string,
  locations: DayLocation[],
  features: TripFeature[],
): (DayLocation | TripFeature)[] => {
  const dayLocs = locations
    .filter((l) => l.trip_day_id === dayId)
    .sort((a, b) => (a.visit_order || 0) - (b.visit_order || 0))
  const dayFeats = features
    .filter((f) => f.trip_day_id === dayId)
    .sort((a, b) => (a.visit_order || 0) - (b.visit_order || 0))
  return [...dayLocs, ...dayFeats].sort((a, b) => (a.visit_order || 0) - (b.visit_order || 0))
}

export const exportTripToPDF = (trip: Trip, dayLocations: DayLocation[], dayFeatures: TripFeature[]) => {
  const doc = new jsPDF()

  // --- Cover Page ---
  doc.setFontSize(24)
  doc.setTextColor(25, 118, 210) // Primary Blue
  doc.text(trip.name, 20, 30)

  doc.setFontSize(12)
  doc.setTextColor(100)
  const dateRange = `${new Date(trip.start_date).toLocaleDateString()} - ${new Date(trip.end_date).toLocaleDateString()}`
  doc.text(dateRange, 20, 40)

  doc.text(`Total Locations: ${dayLocations.length}`, 20, 55)
  doc.text(`Total Features: ${dayFeatures.length}`, 20, 62)

  // Add a horizontal line
  doc.setDrawColor(200)
  doc.line(20, 70, 190, 70)

  // --- Itinerary ---
  let yPos = 80

  if (!trip.days || trip.days.length === 0) {
    doc.text("No itinerary details available.", 20, yPos)
  } else {
    trip.days.forEach((day, index) => {
      // Check for page break
      if (yPos > 250) {
        doc.addPage()
        yPos = 20
      }

      // Day Header
      doc.setFontSize(16)
      doc.setTextColor(0)
      doc.text(`Day ${index + 1}: ${new Date(day.date).toLocaleDateString()}`, 20, yPos)
      yPos += 10

      const items = getDayItems(day.id, dayLocations, dayFeatures)

      if (items.length === 0) {
        doc.setFontSize(10)
        doc.setTextColor(150)
        doc.text("No activities planned.", 25, yPos)
        yPos += 15
      } else {
        // Table for items
        const tableBody = items.map((item) => {
          const isLocation = "city" in item
          let name = isLocation ? item.city : (item as TripFeature).properties?.name || "Unknown"
          const type = isLocation ? "Location" : (item as TripFeature).properties?.type || "Feature"
          const notes = isLocation ? item.notes || "" : (item as TripFeature).properties?.description || ""

          if (!isLocation) {
            const feat = item as TripFeature
            const props = feat.properties || {}
            const address = (props.address as string) || (props.formatted_address as string)
            const phone =
              (props.phone as string) ||
              (props.formatted_phone_number as string) ||
              (props.international_phone_number as string)

            if (address || phone) {
              name += "\n\n"
              if (address) name += `Address: ${address}\n`
              if (phone) name += `Phone: ${phone}`
            }
          }

          let cost = ""
          if (isLocation) {
            cost = item.transport_cost ? `$${item.transport_cost}` : ""
          } else {
            const feat = item as TripFeature
            cost = feat.transport_cost ? `$${feat.transport_cost}` : ""
          }

          return [name, type, notes, cost]
        })

        autoTable(doc, {
          startY: yPos,
          head: [["Name", "Type", "Notes", "Cost"]],
          body: tableBody,
          theme: "striped",
          headStyles: { fillColor: [25, 118, 210] },
          margin: { left: 20 },
          columnStyles: {
            0: { cellWidth: 50, fontStyle: "bold" },
            1: { cellWidth: 30 },
            2: { cellWidth: "auto" },
            3: { cellWidth: 20, halign: "right" },
          },
        })

        // Update yPos after table
        // @ts-expect-error - lastAutoTable is added by the plugin
        yPos = doc.lastAutoTable.finalY + 15
      }
    })
  }

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(10)
    doc.setTextColor(150)
    doc.text(`Page ${i} of ${pageCount}`, 190, 285, { align: "right" })
    doc.text("Generated by Trip Explorer", 20, 285)
  }

  doc.save(`${trip.name.replace(/\s+/g, "_")}_Itinerary.pdf`)
}
